basePath: /api/v1
consumes:
- application/json
definitions:
  controllers.classworkRequestBody:
    properties:
      base:
        description: The base URL for the PowerSchool HAC service
        example: homeaccess.katyisd.org
        type: string
      markingPeriods:
        description: The marking period to pull data from
        example:
        - 1
        - 2
        items:
          type: integer
        type: array
      password:
        description: The password to log in with
        example: j382704
        type: string
      username:
        description: The username to log in with
        example: j1732901
        type: string
    required:
    - base
    - password
    - username
    type: object
  controllers.iprAllRequestBody:
    properties:
      base:
        description: The base URL for the PowerSchool HAC service
        example: homeaccess.katyisd.org
        type: string
      datesOnly:
        default: false
        description: Whether to return only dates or all the IPRs
        example: true
        type: boolean
      password:
        description: The password to log in with
        example: j382704
        type: string
      username:
        description: The username to log in with
        example: j1732901
        type: string
    required:
    - base
    - password
    - username
    type: object
  controllers.iprRequestBody:
    properties:
      base:
        description: The base URL for the PowerSchool HAC service
        example: homeaccess.katyisd.org
        type: string
      date:
        description: The date of the IPR to return
        example: 09/06/2022
        type: string
      password:
        description: The password to log in with
        example: j382704
        type: string
      username:
        description: The username to log in with
        example: j1732901
        type: string
    required:
    - base
    - password
    - username
    type: object
  controllers.loginRequestBody:
    properties:
      base:
        description: The base URL for the PowerSchool HAC service
        example: homeaccess.katyisd.org
        type: string
      password:
        description: The password to register
        example: j382704
        type: string
      username:
        description: The username to register
        example: j1732901
        type: string
    required:
    - base
    - password
    - username
    type: object
  controllers.reportCardRequestBody:
    properties:
      base:
        description: The base URL for the PowerSchool HAC service
        example: homeaccess.katyisd.org
        type: string
      password:
        description: The password to log in with
        example: j382704
        type: string
      username:
        description: The username to log in with
        example: j1732901
        type: string
    required:
    - base
    - password
    - username
    type: object
  models.Absences:
    properties:
      excusedAbsence:
        type: string
      excusedTardy:
        type: string
      unexcusedAbsence:
        type: string
      unexcusedTardy:
        type: string
    type: object
  models.Assignment:
    properties:
      assignedDate:
        description: The date the assignment was assigned
        type: string
      category:
        description: The category of the assignment (major, minor, other, etc)
        type: string
      dropped:
        description: Whether the assignment was dropped or not
        type: boolean
      dueDate:
        description: The date the assignment is due
        type: string
      grade:
        description: What grade the user got on the assignment
        type: string
      name:
        description: The name of the assignment
        type: string
      totalPoints:
        description: The total points that could be earned on the assignment
        type: string
    type: object
  models.Class:
    properties:
      course:
        description: The course ID of the class
        type: string
      name:
        description: The name of the class
        type: string
      period:
        description: What period the class is for the student, relative to the current
          schedule
        type: string
      room:
        description: The room number of the class
        type: string
      teacher:
        description: The name of the teacher of the class
        type: string
    type: object
  models.Classwork:
    properties:
      entries:
        description: An array of ClassworkEntry structs containing classwork for each
          class
        items:
          $ref: '#/definitions/models.ClassworkEntry'
        type: array
      sixWeeks:
        description: The marking period the classwork is for
        type: integer
    type: object
  models.ClassworkEntry:
    properties:
      assignments:
        description: All the assignments currently entered for the class
        items:
          $ref: '#/definitions/models.Assignment'
        type: array
      average:
        description: The average grade for that class
        type: string
      class:
        $ref: '#/definitions/models.Class'
        description: Class information about the entry
      position:
        description: The position of the class, used for ordering
        type: integer
    type: object
  models.ClassworkResponse:
    properties:
      classwork:
        description: The resulting classwork
        items:
          $ref: '#/definitions/models.Classwork'
        type: array
      err:
        description: If there was an error
        type: boolean
      msg:
        description: The associated message
        type: string
    type: object
  models.IPR:
    properties:
      date:
        description: The date the IPR was submitted
        type: string
      entries:
        description: An array representing all the IPR entries
        items:
          $ref: '#/definitions/models.IPREntry'
        type: array
    type: object
  models.IPREntry:
    properties:
      class:
        $ref: '#/definitions/models.Class'
        description: Information about the class related to the IPREntry
      grade:
        description: The average at the moment the progress report was submitted
        type: string
    type: object
  models.IPRResponse:
    properties:
      err:
        description: If there was an error
        type: boolean
      ipr:
        description: The resulting IPR(s)
        items:
          $ref: '#/definitions/models.IPR'
        type: array
      msg:
        description: The associated message
        type: string
    type: object
  models.LoginResponse:
    properties:
      err:
        description: If there was an error
        type: boolean
      msg:
        description: The associated message
        type: string
    type: object
  models.ReportCard:
    properties:
      entries:
        items:
          $ref: '#/definitions/models.ReportCardEntry'
        type: array
    type: object
  models.ReportCardEntry:
    properties:
      absences:
        $ref: '#/definitions/models.Absences'
      attemptedCredit:
        type: string
      averages:
        $ref: '#/definitions/models.SixWeeksGrades'
      class:
        $ref: '#/definitions/models.Class'
      comments:
        $ref: '#/definitions/models.SixWeeksOther'
      conduct:
        $ref: '#/definitions/models.SixWeeksOther'
      earnedCredit:
        type: string
    type: object
  models.ReportCardResponse:
    properties:
      err:
        description: If there was an error
        type: boolean
      msg:
        description: The associated message
        type: string
      reportCard:
        $ref: '#/definitions/models.ReportCard'
        description: The resulting report card
    type: object
  models.SixWeeksGrades:
    properties:
      exam1:
        type: string
      exam2:
        type: string
      fifth:
        type: string
      first:
        type: string
      fourth:
        type: string
      second:
        type: string
      sem1:
        type: string
      sem2:
        type: string
      sixth:
        type: string
      third:
        type: string
    type: object
  models.SixWeeksOther:
    properties:
      fifth:
        type: string
      first:
        type: string
      fourth:
        type: string
      second:
        type: string
      sixth:
        type: string
      third:
        type: string
    type: object
info:
  contact: {}
  description: An API to fetch data from Home Access Center.
  title: HAC Information API
  version: "1.0"
paths:
  /classwork:
    post:
      consumes:
      - application/json
      description: |-
        Returns classwork for the marking periods specified.
        If no marking periods are specified, the classwork for the current marking period is returned.
      parameters:
      - description: Body Params
        in: body
        name: request
        schema:
          $ref: '#/definitions/controllers.classworkRequestBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ClassworkResponse'
      tags:
      - classwork
  /ipr:
    post:
      consumes:
      - application/json
      description: |-
        Returns the IPR(s) for the user. If the date parameter is not passed into the body or is invalid, the most recent IPR is returned.
        It is important the format of the date follows the format "01/02/2006" (01 = month, 02 = day, 2006 = year), with leading zeros like shown in the format.
        For all possible dates, refer to the "/ipr/all" endpoint.
      parameters:
      - description: Body Params
        in: body
        name: request
        schema:
          $ref: '#/definitions/controllers.iprRequestBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.IPRResponse'
      tags:
      - ipr
  /ipr/all:
    post:
      consumes:
      - application/json
      description: Returns all the IPRs for the user, or just the dates depending
        on the DatesOnly parameter's value in the body.
      parameters:
      - description: Body Params
        in: body
        name: request
        schema:
          $ref: '#/definitions/controllers.iprAllRequestBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.IPRResponse'
      tags:
      - ipr
  /login:
    post:
      consumes:
      - application/json
      description: |-
        Pre-registers the user with the API by logging them into HAC early, and caching the cookies.
        Subsequent requests using the same credentials will use these stored cookies, leading to faster response times for other endpoints.
      parameters:
      - description: Body Params
        in: body
        name: request
        schema:
          $ref: '#/definitions/controllers.loginRequestBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.LoginResponse'
      tags:
      - auth
  /reportcard:
    post:
      consumes:
      - application/json
      description: Returns report card data for the user.
      parameters:
      - description: Body params
        in: body
        name: request
        schema:
          $ref: '#/definitions/controllers.reportCardRequestBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ReportCardResponse'
      tags:
      - reportcard
produces:
- application/json
swagger: "2.0"
tags:
- description: Caching a login with the API
  name: auth
- description: Get data about classwork
  name: classwork
- description: Get data about interim progress report(s)
  name: ipr
- description: Get data about the report card
  name: reportcard
